apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    type: web
spec:
  containers:
    - image: nginx
      name: nginx-container
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
    type: web
  ports:
    - port: 80
      targetPort: 80

