apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  name: kruthika
  course: python
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
    - image: nginx
      name: nginx
      envFrom:
        - configMapRef:
            name: test